version: '2'

services:
  redis:
    restart: always
    image: zchee/redis:unstable
    volumes:
      - ./redis:/data
    expose:
      - "6378"
  node:
    build: node/.
    expose:
      - "81"
    volumes:
     - ./node:/usr/src/app
    command: ['nodemon', 'server.js']
  api:
    build: api/.
    expose:
      - "80"
    volumes:
      - ./api:/opt/openresty/nginx/conf
      - ./web:/web
    entrypoint: ""
    command:  bash -c "lapis server development"
networks:
  default:
    external:
      name: webserver_default
