version: '2'

services:
  redis:
    restart: always
    image: zchee/redis:unstable
    volumes:
      - ./redis:/data
    expose:
      - "6378"
  burgerblog:
    build: web/.
    expose:
      - "80"
    volumes:
      - ./web:/opt/openresty/nginx/conf
    entrypoint: ""
    command:  bash -c "lapis server development"
  fe:
    build: fe/.
    expose: 
     - "81"
    volumes:
      - ./fe:/src/
      - /src/node_modules
networks:
  default:
    external:
      name: webserver_default
